COMP: Pass saveFileName by values instead of by reference
On clangCL toolset for Visual Studio 2022 it causes the following error:

M:\Dev\Nornir\ITKNornir\include\itkIRCommon.h(4115,29): error : non-const lvalue reference to type 'the_text_t' cannot bind to a value of unrelated type 'const char[1]'