COMP: Replace NULL by nullptr
This is not merely due to style. Sample error message:

 /Users/svc-dashboard/D/ITKNornir/src/IRGridTransform.cxx
In file included from /Users/svc-dashboard/D/ITKNornir/src/IRGridTransform.cxx:35:
In file included from /Users/svc-dashboard/D/ITKNornir/include/IRGridTransform.h:38:
/Users/svc-dashboard/D/ITKNornir/include/itkIRCommon.h:2979:26: error: ambiguous conversion for functional-style cast from 'long' to 'typename msk_interpolator_t::Pointer' (aka 'SmartPointer<itk::NearestNeighborInterpolateImageFunction<itk::Image<unsigned char, 2>, double>>')
  msk.assign(num_images, typename msk_interpolator_t::Pointer(NULL));
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~